name: Build GHDL

on: 
  #push: 
  schedule:
    - cron: '0 0 * * *'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
jobs:
  build_dep:
    uses: daxzio/setup-eda/.github/workflows/setup_ghdl.yml@main

  build:
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    needs: [build_dep]
    steps:
      - name: Cache GHDL
        uses: actions/cache@v3
        with:
          path: ${{ needs.build_dep.outputs.cache_dir }}
          key: ${{ needs.build_dep.outputs.cache_key }}
      - name: Add to PATH
        run: |
          echo "${{ needs.build_dep.outputs.cache_dir }}/bin" >> $GITHUB_PATH
      
      - name: Report GHDL
        run: |
          sudo apt install gnat
          which ghdl
          ghdl version
