name: Setup Verilator

on: 
  workflow_call:
    inputs:
      githash:
        description: "Allow a githash/tag/branch to be passed as an input"
        required: false
        type: string
    outputs:
      cache_dir:
        description: "The Cache Directory"
        value: ${{ jobs.build.outputs.output0 }}
      cache_key:
        description: "The Cache Key"
        value: ${{ jobs.build.outputs.output1 }}

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      output0 : ${{ steps.step0.outputs.cache_dir }}
      output1 : ${{ steps.step1.outputs.cache_key }}
    steps:
      - name: Test for GITHASH input
        if: ${{ inputs.githash != '' }}
        run: |
          echo "GITHEAD=${{ inputs.githash }}" >> $GITHUB_ENV
      - name: Setup Verilator 
        run: |
          export GITPATH=https://github.com/verilator/verilator.git
          if [ -z ${GITHEAD+x} ]; then
            export GITHEAD=`git ls-remote $GITPATH HEAD | head -1 | awk '{print $1}'`
            echo "GITHEAD=${GITHEAD}" >> $GITHUB_ENV
          fi
          echo "GITPATH=${GITPATH}" >> $GITHUB_ENV
          echo "CACHE_DIR=${{ github.workspace }}/.cache/verilator" >> $GITHUB_ENV
          echo "CACHE_KEY=verilator-${GITHEAD}" >> $GITHUB_ENV
      - name: Cache Environment
        id: git-cache
        uses: actions/cache@v3
        with:
          path: ${{ env.CACHE_DIR }}
          key: ${{ env.CACHE_KEY }}
      - if: ${{ steps.git-cache.outputs.cache-hit != 'true' }}
        name: Compile Verilator 
        run: |
          mkdir -p ${{ env.CACHE_DIR }}
          git clone ${{ env.GITPATH }}
          cd verilator
          git checkout ${{ env.GITHEAD }}
          sudo apt install -y build-essential
          sudo apt install -y git help2man perl python3 make autoconf g++ flex bison ccache
          sudo apt install -y libunwind-dev
          sudo apt install -y libgoogle-perftools-dev numactl perl-doc
          sudo apt install -y libfl2  # Ubuntu only (ignore if gives error)
          sudo apt install -y libfl-dev  # Ubuntu only (ignore if gives error)
          sudo apt install -y zlib1g zlib1g-dev  # Ubuntu only (ignore if gives error)
          autoconf
          ./configure --prefix=${{ env.CACHE_DIR }}
          make -j$(nproc)
          sudo make install
          cd ..
      - id: step0
        run: echo "cache_dir=${{ env.CACHE_DIR }}" >> $GITHUB_OUTPUT
      - id: step1
        run: echo "cache_key=${{ env.CACHE_KEY }}" >> $GITHUB_OUTPUT
