name: Check cached Setup

on: 
  #push: 
  schedule:
    - cron: '0 1 * * *'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
jobs:
#   build_ghdl:
#     uses: ./.github/workflows/setup_ghdl.yml
#   check_ghdl:
#     runs-on: ubuntu-latest
#     needs: build_ghdl
#     steps:
#       - name: Cache GHDL
#         uses: actions/cache@v4
#         with:
#           path: ${{ needs.build_ghdl.outputs.cache_dir }}
#           key: ${{ needs.build_ghdl.outputs.cache_key }}
#       - name: Add to PATH
#         run: |
#           echo "${{ needs.build_ghdl.outputs.cache_dir }}/bin" >> $GITHUB_PATH
#       - name: Report GHDL
#         run: |
#           which ghdl

  build_verilator:
    uses: ./.github/workflows/setup_verilator.yml
  check_verilator:
    runs-on: ubuntu-latest
    needs: build_verilator
    steps:
      - name: Cache verilator
        uses: actions/cache@v4
        with:
          path: ${{ needs.build_verilator.outputs.cache_dir }}
          key: ${{ needs.build_verilator.outputs.cache_key }}
      - name: Add to PATH
        run: |
          echo "${{ needs.build_verilator.outputs.cache_dir }}/bin" >> $GITHUB_PATH
      - name: Report verilator
        run: |
          which verilator

  build_icarus:
    uses: ./.github/workflows/setup_icarus.yml
  check_icarus:
    runs-on: ubuntu-latest
    needs: build_icarus
    steps:
      - name: Cache Icarus
        uses: actions/cache@v4
        with:
          path: ${{ needs.build_icarus.outputs.cache_dir }}
          key: ${{ needs.build_icarus.outputs.cache_key }}
      - name: Add to PATH
        run: |
          echo "${{ needs.build_icarus.outputs.cache_dir }}/bin" >> $GITHUB_PATH
      - name: Report Icarus
        run: |
          which iverilog
